database:
  name: "im_message"
  type: "mysql"
  url: "root:123456@tcp(127.0.0.1:13306)/message"
redis:
  name: "im_message"  
  address: "0.0.0.0:16379"
  password: ""
  db: 0 
  pool_size: 10 
  min_idle: 5  
  max_idle: 10  
  timeout: "5s" 
